# Generated by Django 5.1.15 on 2026-09-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0013_keyword_search_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodexRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20)),
                ('brief', models.TextField()),
                ('seed', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(default='us', max_length=2)),
                ('status', models.CharField(default='queued', max_length=12)),
                ('queue_rank', models.IntegerField(blank=True, null=True)),
                ('progress_message', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('report', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
