# Generated by Django 5.1.15 on 2026-09-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0014_codex_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='codexrun',
            name='competitor_app_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='codexrun',
            name='discovery_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='codexrun',
            name='promoted_app_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
